module JobWorkflow
  interface _JobInterface
    def job_id: () -> String
    def queue_name: () -> String
    def serialize: () -> Hash[String, untyped]
    def _context: () -> JobWorkflow::Context?
    def _context=: (JobWorkflow::Context) -> JobWorkflow::Context
    def step: (Symbol, ?start: ActiveJob::Continuation::_Succ, ?isolated: bool) -> void
            | (Symbol, ?start: ActiveJob::Continuation::_Succ, ?isolated: bool) { (ActiveJob::Continuation::Step) -> void } -> void
  end
end
