module SolidQueue
  class Queue
    def self.find_by_name: (String) -> Queue

    def paused?: () -> bool

    def pause: () -> Pause

    def resume: () -> Integer

    def latency: () -> Integer

    def size: () -> Integer

    def clear: () -> void
  end

  class Pause < Record
    def self.pluck: (Symbol) -> Array[String]
  end

  class Record < ActiveRecord::Base
  end

  class Job < Record
    class EnqueueError < StandardError
    end

    module Executable
      def finished?: () -> bool

      def ready?: () -> bool

      def claimed?: () -> bool

      def failed?: () -> bool
    end

    module Clearable
    end

    module Recurrable
    end

    class ActiveRecord_Relation < ActiveRecord::Relation
      include _ActiveRecord_Relation[Job, Integer]
    end

    extend _ActiveRecord_Relation_ClassMethods[Job, ActiveRecord_Relation, Integer]

    include Executable
    include Clearable
    include Recurrable

    def active_job_id: () -> String

    def class_name: () -> String

    def queue_name: () -> String

    def arguments: () -> Hash[String, untyped]
  end

  class Semaphore < Record
    # Interface expected by wait/signal
    interface _SemaphoreJob
      def concurrency_key: () -> String
      def concurrency_limit: () -> Integer
      def concurrency_duration: () -> ActiveSupport::Duration
    end

    def self.wait: (_SemaphoreJob job) -> bool
    def self.signal: (_SemaphoreJob job) -> bool
    def self.signal_all: (Array[_SemaphoreJob] jobs) -> Integer
  end

  class Configuration
    def recurring_tasks_config: () -> Hash[Symbol, Hash[Symbol, untyped]]
  end
end
